import { Source_Sans_3 } from "next/font/google";
import "./globals.css";

const sans3 = Source_Sans_3({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ['400', '600', '700']
})

export const metadata = {
  title: "Deskflow",
  description: "Generated by Osher Asefa",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sans3.className}>{children}</body>
    </html>
  );
}
